#!/usr/bin/env python3
"""
Auto-generate game entries from HTML files in the games folder
"""

import os
import json
import re

def clean_game_name(filename):
    """Convert filename to readable game title"""
    # Remove .html extension
    name = filename.replace('.html', '')
    # Replace underscores with spaces
    name = name.replace('_', ' ')
    # Handle special cases
    name = name.replace('  ', ' - ')
    return name

def generate_game_id(filename):
    """Generate a unique game ID from filename"""
    return filename.replace('.html', '').lower().replace('_', '-')

def get_color_gradient(index):
    """Generate color gradients cycling through different colors"""
    colors = [
        "from-red-500 to-orange-500",
        "from-blue-500 to-purple-600",
        "from-green-500 to-teal-500",
        "from-yellow-500 to-orange-600",
        "from-purple-500 to-pink-500",
        "from-indigo-500 to-blue-600",
        "from-pink-500 to-rose-600",
        "from-cyan-500 to-blue-500",
        "from-lime-500 to-green-600",
        "from-amber-500 to-orange-600",
    ]
    return colors[index % len(colors)]

def main():
    # Check both possible locations
    games_dirs = ['./public/games', './games']
    games_dir = None
    
    for dir_path in games_dirs:
        if os.path.exists(dir_path):
            games_dir = dir_path
            break
    
    if not games_dir:
        print("❌ Error: games folder not found!")
        print("\n📁 Please move your games folder to one of these locations:")
        print("   1. ./public/games (recommended for Vite)")
        print("   2. ./games")
        print("\nThen run this script again.")
        return
    
    print(f"✅ Found games folder at: {games_dir}")
    
    # Get all HTML files
    html_files = [f for f in os.listdir(games_dir) if f.endswith('.html')]
    html_files.sort()  # Sort alphabetically
    
    print(f"✅ Found {len(html_files)} game files!")
    
    # Generate TypeScript code
    ts_code = """import { Game } from './types';

// Auto-generated games from /games folder
// Generated by generate_all_games.py
export const HTML_GAMES: Game[] = [
"""
    
    for index, filename in enumerate(html_files):
        game_id = generate_game_id(filename)
        game_title = clean_game_name(filename)
        color = get_color_gradient(index)
        
        game_entry = f"""  {{ id: "{game_id}", title: "{game_title}", platform: "PC", system: "HTML5", year: "2024", color: "{color}", desc: "Play {game_title} directly in your browser", icon: "fa-gamepad", iconColor: "text-white", image: "", link: "/games/{filename}" }},
"""
        ts_code += game_entry
    
    # Close the array
    ts_code += "];\n"
    
    # Write to htmlGames.ts
    output_file = 'htmlGames.ts'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_code)
    
    print(f"\n✅ Successfully generated {output_file}")
    print(f"✅ Added {len(html_files)} games to the file")
    print(f"\n🎮 Games are now available in your Games Hub!")
    print(f"\n📋 Some examples:")
    for i, filename in enumerate(html_files[:5]):
        print(f"  - {clean_game_name(filename)}")
    if len(html_files) > 5:
        print(f"  ... and {len(html_files) - 5} more!")
    
    print(f"\n⚠️  IMPORTANT: Make sure your games folder is at ./public/games")
    print(f"   Current location: {games_dir}")
    if games_dir == './games':
        print(f"\n   Run this command to move it:")
        print(f"   Move-Item -Path ./games -Destination ./public/games")

if __name__ == "__main__":
    main()
